set(MINUIT_SOURCES 
minuit/code/minuit.F 
minuit/code/mnamin.F 
minuit/code/mnbins.F 
minuit/code/mncalf.F 
minuit/code/mncler.F 
minuit/code/mncntr.F 
minuit/code/mncomd.F 
minuit/code/mncont.F 
minuit/code/mncrck.F 
minuit/code/mncros.F 
minuit/code/mncuve.F 
minuit/code/mnderi.F 
minuit/code/mndxdi.F 
minuit/code/mneig.F  
minuit/code/mnemat.F 
minuit/code/mnerrs.F 
minuit/code/mneval.F 
minuit/code/mnexcm.F 
minuit/code/mnexin.F 
minuit/code/mnfixp.F 
minuit/code/mnfree.F 
minuit/code/mngrad.F 
minuit/code/mnhelp.F 
minuit/code/mnhes1.F 
minuit/code/mnhess.F 
minuit/code/mnimpr.F 
minuit/code/mninex.F 
minuit/code/mninit.F 
minuit/code/mninpu.F 
minuit/code/mnintr.F 
minuit/code/mnlims.F 
minuit/code/mnline.F 
minuit/code/mnmatu.F 
minuit/code/mnmigr.F 
minuit/code/mnmnos.F 
minuit/code/mnmnot.F 
minuit/code/mnparm.F 
minuit/code/mnpars.F 
minuit/code/mnpfit.F 
minuit/code/mnpint.F 
minuit/code/mnplot.F 
minuit/code/mnpout.F 
minuit/code/mnprin.F 
minuit/code/mnpsdf.F 
minuit/code/mnrazz.F 
minuit/code/mnread.F 
minuit/code/mnrn15.F 
minuit/code/mnrset.F 
minuit/code/mnsave.F 
minuit/code/mnscan.F 
minuit/code/mnseek.F 
minuit/code/mnset.F  
minuit/code/mnseti.F 
minuit/code/mnsimp.F 
minuit/code/mnstat.F 
minuit/code/mnstin.F 
minuit/code/mntiny.F 
minuit/code/mnunpt.F 
minuit/code/mnvers.F 
minuit/code/mnvert.F 
minuit/code/mnwarn.F 
minuit/code/mnwerr.F 
minuit/code/stand.F 
)
